version: '3.7'

services:

  storage:
    container_name: drive
    image:  registry.storage-project.ir:5000/storage/storage-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'