version: '3.7'

services:

  storage:
    container_name: drive
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/drive'
      - '/drive/node_modules'  
    ports:
      - '3000:3000'